const BulkPort = [process.env.PUBLIC_URL+'/PortPics/0.jpg',
process.env.PUBLIC_URL+'/PortPics/1.jpg',
process.env.PUBLIC_URL+'/PortPics/2.jpg',
process.env.PUBLIC_URL+'/PortPics/3.jpg',
process.env.PUBLIC_URL+'/PortPics/4.jpg',
process.env.PUBLIC_URL+'/PortPics/5.jpg',
process.env.PUBLIC_URL+'/PortPics/6.jpg',
process.env.PUBLIC_URL+'/PortPics/7.jpg',
process.env.PUBLIC_URL+'/PortPics/8.jpg',
process.env.PUBLIC_URL+'/PortPics/9.jpg',
process.env.PUBLIC_URL+'/PortPics/10.jpg',
process.env.PUBLIC_URL+'/PortPics/11.jpg',
process.env.PUBLIC_URL+'/PortPics/12.jpg',
process.env.PUBLIC_URL+'/PortPics/13.jpg',
process.env.PUBLIC_URL+'/PortPics/14.jpg',
process.env.PUBLIC_URL+'/PortPics/15.jpg',
]
export default BulkPort