const BulkPort = [process.env.PUBLIC_URL+'/PortPics/0.WebP',
process.env.PUBLIC_URL+'/PortPics/1.WebP',
process.env.PUBLIC_URL+'/PortPics/2.WebP',
process.env.PUBLIC_URL+'/PortPics/3.WebP',
process.env.PUBLIC_URL+'/PortPics/4.WebP',
process.env.PUBLIC_URL+'/PortPics/5.WebP',
process.env.PUBLIC_URL+'/PortPics/6.WebP',
process.env.PUBLIC_URL+'/PortPics/7.WebP',
process.env.PUBLIC_URL+'/PortPics/8.WebP',
process.env.PUBLIC_URL+'/PortPics/9.WebP',
process.env.PUBLIC_URL+'/PortPics/10.WebP',
process.env.PUBLIC_URL+'/PortPics/11.WebP',
process.env.PUBLIC_URL+'/PortPics/12.WebP',
process.env.PUBLIC_URL+'/PortPics/13.WebP',
process.env.PUBLIC_URL+'/PortPics/14.WebP',
process.env.PUBLIC_URL+'/PortPics/15.WebP',
]
export default BulkPort