const bulkLand = [process.env.PUBLIC_URL+'/LandPics/0.WebP',
process.env.PUBLIC_URL+'/LandPics/1.WebP',
process.env.PUBLIC_URL+'/LandPics/2.WebP',
process.env.PUBLIC_URL+'/LandPics/3.WebP',
process.env.PUBLIC_URL+'/LandPics/4.WebP',
process.env.PUBLIC_URL+'/LandPics/5.WebP',
process.env.PUBLIC_URL+'/LandPics/6.WebP',
process.env.PUBLIC_URL+'/LandPics/7.WebP',
process.env.PUBLIC_URL+'/LandPics/8.WebP',
process.env.PUBLIC_URL+'/LandPics/9.WebP',
process.env.PUBLIC_URL+'/LandPics/10.WebP',
process.env.PUBLIC_URL+'/LandPics/11.WebP',
process.env.PUBLIC_URL+'/LandPics/12.WebP',
process.env.PUBLIC_URL+'/LandPics/13.WebP',
process.env.PUBLIC_URL+'/LandPics/14.WebP',
process.env.PUBLIC_URL+'/LandPics/15.WebP',
process.env.PUBLIC_URL+'/LandPics/16.WebP',
process.env.PUBLIC_URL+'/LandPics/17.WebP',
process.env.PUBLIC_URL+'/LandPics/18.WebP',
process.env.PUBLIC_URL+'/LandPics/19.WebP',
process.env.PUBLIC_URL+'/LandPics/20.WebP',
]


export default bulkLand